name=RYLR998
version=1.0.0
author=charly
maintainer=charly
sentence=Librería para controlar el módulo LoRa RYLR998 con ESP32 en Arduino IDE
paragraph=Permite inicializar, configurar, enviar y recibir mensajes de forma sencilla usando ESP32.
category=Communication
url=https://github.com/soy-charly/esp32-RYLR998
architectures=esp32


